services:
  postgres:
    image: postgres:14-alpine
    container_name: fastapi_app_postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - db

networks:
  db:
    external: true