"""delete_author_model

Revision ID: 2fc1d800ad09
Revises: 0c4c0bba4a82
Create Date: 2024-06-28 14:52:49.684410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fc1d800ad09'
down_revision: Union[str, None] = '0c4c0bba4a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_posts_t_author_id_fkey', 'blog_posts_t', type_='foreignkey')
    op.drop_column('blog_posts_t', 'author_id')
    op.add_column('blog_posts_t', sa.Column('author', sa.String(), nullable=True))
    op.drop_table('authors_t')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts_t', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('blog_posts_t_author_id_fkey', 'blog_posts_t', 'authors_t', ['author_id'], ['id'])
    op.drop_column('blog_posts_t', 'author')
    op.create_table('authors_t',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='authors_t_pkey'),
    sa.UniqueConstraint('name', name='authors_t_name_key')
    )
    # ### end Alembic commands ###
